name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    - name: Install dependencies
      run: |
        go version
        go mod download
    - name: Run Test
      run: |
        go test -v -count=10 ./...
