on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Install dependencies
      run: |
        go version
        go mod download
    - name: Run Test
      run: |
        go test -v -count=1 ./...
